# Generated by Django 5.0.2 on 2024-03-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
