# Generated by Django 5.0.2 on 2024-03-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comment_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
