# Generated by Django 5.0.2 on 2024-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_solded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='solded',
            new_name='sold_date',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='sold',
            new_name='sold_is',
        ),
        migrations.AddField(
            model_name='listing',
            name='sold_price',
            field=models.IntegerField(null=True),
            preserve_default=False,
        ),
    ]
