# Generated by Django 5.0.2 on 2024-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_solded_listing_sold_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
