# Generated by Django 5.0.2 on 2024-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_listing_sold_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sold_price',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
