# Generated by Django 5.0.2 on 2024-03-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_sold_date_alter_listing_sold_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
