# Generated by Django 5.0.2 on 2024-03-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
