# Generated by Django 5.0.2 on 2024-03-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_rename_name_listing_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
    ]
