# Generated by Django 5.0.2 on 2024-03-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_rename_title_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default=30547, max_length=12),
        ),
    ]
