# Generated by Django 5.0.2 on 2024-03-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='User#53148', max_length=12),
        ),
    ]
