# Generated by Django 5.0.2 on 2024-03-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_category_image_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='User#29117', max_length=12),
        ),
    ]
